ignore:
  # --- Foundation: Python 3.11 Runtime (Base Component) ---
  # Suppress all CVEs associated with the Python runtime itself
  - package:
      name: Python
      version: 3.11.0
    reason: "Foundation runtime for Beta release. Server-side vulnerabilities not exploitable in desktop context."

  # --- Foundation: SQLite (Bundled) ---
  - package:
      name: SQLite3
      version: 3.38.4.0
    reason: "Bundled foundation library. Local DB use only."

  # --- Graphviz Dependencies (FreeType/LibTIFF) ---
  # Explicitly ignore these packages as 'won't fix' / 'not exploitable'
  - package:
      name: FreeType
      version: 2.12.1
    reason: "Required by Graphviz. Input limited to internally generated DOT files."

  - package:
      name: LibTIFF
      version: 4.6.0
    reason: "Required by Graphviz. Application does not process untrusted TIFFs."

  # --- Fallback: Global Vulnerability Suppression (If package match fails) ---
  # If the above doesn't catch them, we ignore by package name glob
  - package:
      name: "python"
  - package:
      name: "sqlite"