import os

def get_comment_syntax(file_extension):
    """
    Returns (start_comment, end_comment).
    Returns None if the file type is not supported for watermarking.
    """

    # Hash-style comments
    hash_style = {'.py', '.sh', '.yaml', '.yml', '.rb', '.pl', '.dockerfile', '.conf', '.gitignore'}

    # Double-slash style (C-family, JS, etc.)
    slash_style = {'.js', '.ts', '.java', '.cpp', '.c', '.cs', '.go', '.rs', '.php', '.swift', '.dart'}

    # HTML/XML style
    xml_style = {'.html', '.xml', '.md', '.aspx', '.jsp', '.vue', '.csproj', '.yml', '.user'}

    # CSS style
    css_style = {'.css', '.scss', '.sass', '.less', '.qss'}

    # SQL style
    sql_style = {'.sql'}

    # Batch files
    bat_style = {'.bat', '.cmd'}

    ext = file_extension.lower()

    if ext in hash_style:
        return "# ", ""
    elif ext in slash_style:
        return "// ", ""
    elif ext in xml_style:
        return "<!-- ","-->"
    elif ext in css_style:
        return "/* ", " */"
    elif ext in sql_style:
        return "-- ", ""
    elif ext in bat_style:
        return "REM ", ""
    elif ext == '.txt':
        return "", ""  # Special case: No comment syntax, just append text
    else:
        return None  # UNKNOWN/BINARY TYPE - DO NOT TOUCH

def generate_watermark(filename):
    # Handle Dockerfiles without extensions
    if os.path.basename(filename).lower() == 'dockerfile':
        syntax = ("# ", "")
    else:
        _, ext = os.path.splitext(filename)
        syntax = get_comment_syntax(ext)

    # If syntax is None, this is a binary or unknown file. Abort.
    if syntax is None:
        return None

    start_tag, end_tag = syntax
    watermark_text = "Generated by Klyve AI Automated Software Factory"

    return f"\n\n{start_tag}{watermark_text}{end_tag}\n"

def apply_watermark(file_path):
    try:
        if not os.path.exists(file_path):
            return

        # Check if we should watermark this file type at all
        watermark = generate_watermark(file_path)
        if watermark is None:
            return  # Safety exit for binary files

        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()

        if "Generated by Klyve" in content:
            return

        with open(file_path, 'a', encoding='utf-8') as f:
            f.write(watermark)

    except Exception as e:
        # Silently fail or log error, but don't crash the main app
        print(f"Watermark skipped for {file_path}: {e}")