# gui/import_issue_dialog.py

from PySide6.QtWidgets import QDialog, QMessageBox, QDialogButtonBox

# This import is generated by the uic command you just ran
from gui.ui_import_issue_dialog import Ui_ImportIssueDialog

class ImportIssueDialog(QDialog):
    """
    The logic handler for the dialog that prompts the user for an issue to import.
    """
    def __init__(self, parent=None):
        super().__init__(parent)
        self.ui = Ui_ImportIssueDialog()
        self.ui.setupUi(self)

        # Connect the main OK/Cancel buttons
        self.ui.buttonBox.accepted.connect(self.on_accept)
        self.ui.buttonBox.rejected.connect(self.reject)

        # Set the default button text for clarity
        self.ui.buttonBox.button(QDialogButtonBox.Ok).setText("Import")

    def on_accept(self):
        """
        Validates the input before allowing the dialog to be accepted.
        """
        current_tab_index = self.ui.tabWidget.currentIndex()

        # Tab 0 is "Import by ID"
        if current_tab_index == 0:
            if not self.ui.issueIdLineEdit.text().strip():
                QMessageBox.warning(self, "Input Required", "Please enter an Issue ID.")
                return # Prevent dialog from closing

        # Tab 1 is "Import by Query"
        elif current_tab_index == 1:
            if not self.ui.queryTextEdit.toPlainText().strip():
                QMessageBox.warning(self, "Input Required", "Please enter a query string.")
                return # Prevent dialog from closing

        # If validation passes, accept the dialog
        self.accept()

    def get_data(self) -> dict:
        """
        Returns the data entered by the user in a structured format.
        This should be called after the dialog has been accepted.
        """
        current_tab_index = self.ui.tabWidget.currentIndex()

        if current_tab_index == 0:
            return {
                "mode": "id",
                "value": self.ui.issueIdLineEdit.text().strip()
            }
        else: # Tab 1
            return {
                "mode": "query",
                "value": self.ui.queryTextEdit.toPlainText().strip()
            }