# gui/project_settings_dialog.py
import json
from PySide6.QtWidgets import QDialog
from PySide6.QtCore import Qt

# This import is generated by the uic command
from gui.ui_project_settings_dialog import Ui_ProjectSettingsDialog

class ProjectSettingsDialog(QDialog):
    """
    The logic handler for the project-specific settings dialog.
    """
    def __init__(self, current_settings: dict, parent=None):
        super().__init__(parent)
        self.ui = Ui_ProjectSettingsDialog()
        self.ui.setupUi(self)

        self.connect_signals()
        self.populate_data(current_settings)

    def connect_signals(self):
        """Connects UI element signals to their handler methods."""
        self.ui.providerComboBox.currentIndexChanged.connect(self.on_provider_changed)
        self.ui.buttonBox.accepted.connect(self.accept)
        self.ui.buttonBox.rejected.connect(self.reject)

    def on_provider_changed(self, index: int):
        """Switches the visible form based on the selected provider."""
        self.ui.providerStackedWidget.setCurrentIndex(index)

    def populate_data(self, settings: dict):
        """Pre-populates the dialog with the project's current settings."""
        provider = settings.get("provider", "None")

        # Find and set the provider in the combo box
        provider_index = self.ui.providerComboBox.findText(provider, Qt.MatchFixedString)
        if provider_index >= 0:
            self.ui.providerComboBox.setCurrentIndex(provider_index)

        # Manually trigger the page switch in case the initial index is not 0
        self.on_provider_changed(provider_index)

        # Populate the Jira-specific fields
        if provider == "Jira":
            self.ui.projectKeyLineEdit.setText(settings.get("project_key", ""))
            self.ui.issueTypeIdLineEdit.setText(settings.get("issue_type_id", ""))

    def get_data(self) -> dict:
        """Returns the new settings from the dialog in a structured dictionary."""
        provider = self.ui.providerComboBox.currentText()
        if provider == "None":
            return {"provider": "None"}

        if provider == "Jira":
            return {
                "provider": "Jira",
                "project_key": self.ui.projectKeyLineEdit.text().strip(),
                "issue_type_id": self.ui.issueTypeIdLineEdit.text().strip()
            }

        # Return a default for any future providers that might be added to the UI
        return {"provider": provider}