# gui/project_settings_dialog.py
import json
from PySide6.QtWidgets import QDialog
from PySide6.QtCore import Qt

# This import is generated by the uic command
from gui.ui_project_settings_dialog import Ui_ProjectSettingsDialog

class ProjectSettingsDialog(QDialog):
    """
    The logic handler for the project-specific settings dialog.
    """
    def __init__(self, current_settings: dict, parent=None):
        super().__init__(parent)
        self.ui = Ui_ProjectSettingsDialog()
        self.ui.setupUi(self)

        self.connect_signals()
        self.populate_data(current_settings)

    def connect_signals(self):
        """Connects UI element signals to their handler methods."""
        self.ui.providerComboBox.currentIndexChanged.connect(self.on_provider_changed)
        self.ui.buttonBox.accepted.connect(self.accept)
        self.ui.buttonBox.rejected.connect(self.reject)

    def on_provider_changed(self, index: int):
        """Switches the visible form based on the selected provider."""
        self.ui.providerStackedWidget.setCurrentIndex(index)

    def populate_data(self, settings: dict):
        """Pre-populates the dialog with the project's current settings."""
        provider = settings.get("provider", "None")

        provider_index = self.ui.providerComboBox.findText(provider, Qt.MatchFixedString)
        if provider_index >= 0:
            self.ui.providerComboBox.setCurrentIndex(provider_index)

        self.on_provider_changed(provider_index)

        if provider == "Jira":
            self.ui.projectKeyLineEdit.setText(settings.get("project_key", ""))
            # Pre-populate with common defaults if not set
            self.ui.epicTypeIdLineEdit.setText(settings.get("epic_type_id", "10001"))
            self.ui.storyTypeIdLineEdit.setText(settings.get("story_type_id", "10004"))
            self.ui.taskTypeIdLineEdit.setText(settings.get("task_type_id", "10003"))
            self.ui.bugTypeIdLineEdit.setText(settings.get("bug_type_id", ""))
            self.ui.changeRequestTypeIdLineEdit.setText(settings.get("change_request_type_id", ""))

    def get_data(self) -> dict:
        """Returns the new settings from the dialog in a structured dictionary."""
        provider = self.ui.providerComboBox.currentText()
        if provider == "None":
            return {"provider": "None"}

        if provider == "Jira":
            return {
                "provider": "Jira",
                "project_key": self.ui.projectKeyLineEdit.text().strip(),
                "epic_type_id": self.ui.epicTypeIdLineEdit.text().strip(),
                "story_type_id": self.ui.storyTypeIdLineEdit.text().strip(),
                "task_type_id": self.ui.taskTypeIdLineEdit.text().strip(),
                "bug_type_id": self.ui.bugTypeIdLineEdit.text().strip(),
                "change_request_type_id": self.ui.changeRequestTypeIdLineEdit.text().strip()
            }

        return {"provider": provider}