# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QHeaderView, QLabel, QMainWindow,
    QMenu, QMenuBar, QSizePolicy, QSplitter,
    QStackedWidget, QStatusBar, QTabWidget, QTableView,
    QToolBar, QTreeView, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1200, 800)
        self.actionNew_Project = QAction(MainWindow)
        self.actionNew_Project.setObjectName(u"actionNew_Project")
        self.actionLoad_Archived_Project = QAction(MainWindow)
        self.actionLoad_Archived_Project.setObjectName(u"actionLoad_Archived_Project")
        self.actionStop_Export_Project = QAction(MainWindow)
        self.actionStop_Export_Project.setObjectName(u"actionStop_Export_Project")
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionToggle_Project_Panel = QAction(MainWindow)
        self.actionToggle_Project_Panel.setObjectName(u"actionToggle_Project_Panel")
        self.actionToggle_Notification_Panel = QAction(MainWindow)
        self.actionToggle_Notification_Panel.setObjectName(u"actionToggle_Notification_Panel")
        self.actionView_Documents = QAction(MainWindow)
        self.actionView_Documents.setObjectName(u"actionView_Documents")
        self.actionView_Reports = QAction(MainWindow)
        self.actionView_Reports.setObjectName(u"actionView_Reports")
        self.actionRun_Impact_Analysis = QAction(MainWindow)
        self.actionRun_Impact_Analysis.setObjectName(u"actionRun_Impact_Analysis")
        self.actionProceed = QAction(MainWindow)
        self.actionProceed.setObjectName(u"actionProceed")
        self.actionRun_Full_Test_Suite = QAction(MainWindow)
        self.actionRun_Full_Test_Suite.setObjectName(u"actionRun_Full_Test_Suite")
        self.actionView_Help = QAction(MainWindow)
        self.actionView_Help.setObjectName(u"actionView_Help")
        self.actionAbout_ASDF = QAction(MainWindow)
        self.actionAbout_ASDF.setObjectName(u"actionAbout_ASDF")
        self.actionCheck_for_Updates = QAction(MainWindow)
        self.actionCheck_for_Updates.setObjectName(u"actionCheck_for_Updates")
        self.actionRaise_CR = QAction(MainWindow)
        self.actionRaise_CR.setObjectName(u"actionRaise_CR")
        self.actionReport_Bug = QAction(MainWindow)
        self.actionReport_Bug.setObjectName(u"actionReport_Bug")
        self.actionRun_Risk_Assessment = QAction(MainWindow)
        self.actionRun_Risk_Assessment.setObjectName(u"actionRun_Risk_Assessment")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.mainSplitter = QSplitter(self.centralwidget)
        self.mainSplitter.setObjectName(u"mainSplitter")
        self.mainSplitter.setOrientation(Qt.Horizontal)
        self.mainSplitter.setHandleWidth(1)
        self.leftPanelWidget = QWidget(self.mainSplitter)
        self.leftPanelWidget.setObjectName(u"leftPanelWidget")
        self.leftPanelWidget.setMinimumSize(QSize(250, 0))
        self.leftPanelWidget.setMaximumSize(QSize(400, 16777215))
        self.leftPanelLayout = QVBoxLayout(self.leftPanelWidget)
        self.leftPanelLayout.setObjectName(u"leftPanelLayout")
        self.projectNavigationTabs = QTabWidget(self.leftPanelWidget)
        self.projectNavigationTabs.setObjectName(u"projectNavigationTabs")
        self.filesTab = QWidget()
        self.filesTab.setObjectName(u"filesTab")
        self.verticalLayout_2 = QVBoxLayout(self.filesTab)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.projectFilesTreeView = QTreeView(self.filesTab)
        self.projectFilesTreeView.setObjectName(u"projectFilesTreeView")

        self.verticalLayout_2.addWidget(self.projectFilesTreeView)

        self.projectNavigationTabs.addTab(self.filesTab, "")
        self.changesTab = QWidget()
        self.changesTab.setObjectName(u"changesTab")
        self.verticalLayout_3 = QVBoxLayout(self.changesTab)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.crTableView = QTableView(self.changesTab)
        self.crTableView.setObjectName(u"crTableView")

        self.verticalLayout_3.addWidget(self.crTableView)

        self.projectNavigationTabs.addTab(self.changesTab, "")

        self.leftPanelLayout.addWidget(self.projectNavigationTabs)

        self.mainSplitter.addWidget(self.leftPanelWidget)
        self.mainContentArea = QStackedWidget(self.mainSplitter)
        self.mainContentArea.setObjectName(u"mainContentArea")
        self.welcomePage = QWidget()
        self.welcomePage.setObjectName(u"welcomePage")
        self.verticalLayout_4 = QVBoxLayout(self.welcomePage)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.welcomeLabel = QLabel(self.welcomePage)
        self.welcomeLabel.setObjectName(u"welcomeLabel")
        self.welcomeLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_4.addWidget(self.welcomeLabel)

        self.mainContentArea.addWidget(self.welcomePage)
        self.phasePage = QWidget()
        self.phasePage.setObjectName(u"phasePage")
        self.verticalLayout_5 = QVBoxLayout(self.phasePage)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.phaseLabel = QLabel(self.phasePage)
        self.phaseLabel.setObjectName(u"phaseLabel")

        self.verticalLayout_5.addWidget(self.phaseLabel)

        self.mainContentArea.addWidget(self.phasePage)
        self.mainSplitter.addWidget(self.mainContentArea)

        self.verticalLayout.addWidget(self.mainSplitter)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1200, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuProject = QMenu(self.menubar)
        self.menuProject.setObjectName(u"menuProject")
        self.menuRun = QMenu(self.menubar)
        self.menuRun.setObjectName(u"menuRun")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addAction(self.actionLoad_Archived_Project)
        self.menuFile.addAction(self.actionStop_Export_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuView.addAction(self.actionToggle_Project_Panel)
        self.menuView.addAction(self.actionToggle_Notification_Panel)
        self.menuProject.addAction(self.actionView_Documents)
        self.menuProject.addAction(self.actionView_Reports)
        self.menuProject.addAction(self.actionRun_Impact_Analysis)
        self.menuProject.addAction(self.actionRun_Risk_Assessment)
        self.menuRun.addAction(self.actionProceed)
        self.menuRun.addAction(self.actionRun_Full_Test_Suite)
        self.menuHelp.addAction(self.actionView_Help)
        self.menuHelp.addAction(self.actionCheck_for_Updates)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_ASDF)
        self.toolBar.addAction(self.actionProceed)
        self.toolBar.addAction(self.actionRun_Full_Test_Suite)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRaise_CR)
        self.toolBar.addAction(self.actionReport_Bug)

        self.retranslateUi(MainWindow)

        self.projectNavigationTabs.setCurrentIndex(0)
        self.mainContentArea.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"ASDF - Autonomous Software Development Factory", None))
        self.actionNew_Project.setText(QCoreApplication.translate("MainWindow", u"New Project...", None))
#if QT_CONFIG(shortcut)
        self.actionNew_Project.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionLoad_Archived_Project.setText(QCoreApplication.translate("MainWindow", u"Load Archived Project...", None))
#if QT_CONFIG(shortcut)
        self.actionLoad_Archived_Project.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionStop_Export_Project.setText(QCoreApplication.translate("MainWindow", u"Stop & Export Project...", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Settings...", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
#if QT_CONFIG(shortcut)
        self.actionCut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(shortcut)
        self.actionCopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
#if QT_CONFIG(shortcut)
        self.actionPaste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionToggle_Project_Panel.setText(QCoreApplication.translate("MainWindow", u"Toggle Project Panel", None))
        self.actionToggle_Notification_Panel.setText(QCoreApplication.translate("MainWindow", u"Toggle Notification Panel", None))
        self.actionView_Documents.setText(QCoreApplication.translate("MainWindow", u"View Documents", None))
        self.actionView_Reports.setText(QCoreApplication.translate("MainWindow", u"View Reports", None))
        self.actionRun_Impact_Analysis.setText(QCoreApplication.translate("MainWindow", u"Run Impact Analysis...", None))
        self.actionProceed.setText(QCoreApplication.translate("MainWindow", u"Proceed with Next Step", None))
#if QT_CONFIG(tooltip)
        self.actionProceed.setToolTip(QCoreApplication.translate("MainWindow", u"Proceed with Next Step (F5)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionProceed.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.actionRun_Full_Test_Suite.setText(QCoreApplication.translate("MainWindow", u"Run Full Test Suite", None))
#if QT_CONFIG(tooltip)
        self.actionRun_Full_Test_Suite.setToolTip(QCoreApplication.translate("MainWindow", u"Run Full Test Suite", None))
#endif // QT_CONFIG(tooltip)
        self.actionView_Help.setText(QCoreApplication.translate("MainWindow", u"View Help", None))
#if QT_CONFIG(shortcut)
        self.actionView_Help.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout_ASDF.setText(QCoreApplication.translate("MainWindow", u"About ASDF", None))
        self.actionCheck_for_Updates.setText(QCoreApplication.translate("MainWindow", u"Check for Updates...", None))
        self.actionRaise_CR.setText(QCoreApplication.translate("MainWindow", u"Raise CR", None))
#if QT_CONFIG(tooltip)
        self.actionRaise_CR.setToolTip(QCoreApplication.translate("MainWindow", u"Raise New Change Request", None))
#endif // QT_CONFIG(tooltip)
        self.actionReport_Bug.setText(QCoreApplication.translate("MainWindow", u"Report Bug", None))
#if QT_CONFIG(tooltip)
        self.actionReport_Bug.setToolTip(QCoreApplication.translate("MainWindow", u"Report Operational Bug", None))
#endif // QT_CONFIG(tooltip)
        self.actionRun_Risk_Assessment.setText(QCoreApplication.translate("MainWindow", u"Run Execution Risk Assessment...", None))
#if QT_CONFIG(tooltip)
        self.actionRun_Risk_Assessment.setToolTip(QCoreApplication.translate("MainWindow", u"Run an on-demand risk assessment for the current project", None))
#endif // QT_CONFIG(tooltip)
        self.projectNavigationTabs.setTabText(self.projectNavigationTabs.indexOf(self.filesTab), QCoreApplication.translate("MainWindow", u"Files", None))
        self.projectNavigationTabs.setTabText(self.projectNavigationTabs.indexOf(self.changesTab), QCoreApplication.translate("MainWindow", u"Changes", None))
        self.welcomeLabel.setText(QCoreApplication.translate("MainWindow", u"Welcome to ASDF. Please create a New Project or Load an Archived Project to begin.", None))
        self.phaseLabel.setText(QCoreApplication.translate("MainWindow", u"This is where the UI for a specific project phase will be rendered.", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuProject.setTitle(QCoreApplication.translate("MainWindow", u"Project", None))
        self.menuRun.setTitle(QCoreApplication.translate("MainWindow", u"Run", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

