import logging
import json
import re
from llm_service import LLMService, parse_llm_json
import vault

"""
This module contains the FixPlannerAgent_AppTarget class.
"""

# Configure basic logging
#logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class FixPlannerAgent_AppTarget:
    """
    Agent responsible for creating a detailed plan to fix a bug.

    Based on a root cause hypothesis from the TriageAgent, this agent
    generates a micro-specification for change that instructs other agents
    on how to modify the code to resolve the issue.
    """

    def __init__(self, llm_service: LLMService):
        """
        Initializes the FixPlannerAgent_AppTarget.

        Args:
            llm_service (LLMService): An instance of a class that adheres to the LLMService interface.
        """
        if not llm_service:
            raise ValueError("llm_service is required for the FixPlannerAgent_AppTarget.")
        self.llm_service = llm_service

    def create_fix_plan(self, root_cause_hypothesis: str, relevant_code: str, tech_spec: str) -> str:
        """
        Generates a detailed, sequential JSON plan to fix a diagnosed bug.
        """
        try:
            prompt = vault.get_prompt("agent_fix_planner_app_target__prompt_37").format(root_cause_hypothesis=root_cause_hypothesis, relevant_code=relevant_code, tech_spec=tech_spec)

            response_text = self.llm_service.generate_text(prompt, task_complexity="complex")

            # --- FIX: ROBUST JSON EXTRACTION ---
            json_match = re.search(r'\[.*\]', response_text, re.DOTALL)

            if json_match:
                cleaned_response = json_match.group(0)
            else:
                # Fallback: if no brackets found, try parsing the raw text (sometimes LLM forgets brackets)
                logging.warning("FixPlannerAgent: No JSON array brackets found in response. Attempting raw parse.")
                cleaned_response = response_text

            # Parse via the service to validate and fix minor syntax errors (like trailing commas)
            parsed_json = parse_llm_json(cleaned_response)

            # --- CRITICAL FIX ---
            # Return a clean, valid JSON string generated by Python.
            # This prevents json.loads() in the Orchestrator from crashing due to formatting issues.
            return json.dumps(parsed_json)
            # --------------------

        except Exception as e:
            error_message = f"An error occurred during fix plan generation: {e}"
            logging.error(error_message)
            logging.debug(f"Raw LLM Response was: {response_text if 'response_text' in locals() else 'N/A'}")
            raise e