import logging
import google.generativeai as genai
from typing import Optional

"""
This module contains the CodeAgent_AppTarget class.
"""

class CodeAgent_AppTarget:
    """
    Agent responsible for generating the actual source code for a target
    application component. It translates a logical plan into a specific
    programming language, adhering to the project's coding standard.
    """

    def __init__(self, api_key: str):
        """
        Initializes the CodeAgent_AppTarget.

        Args:
            api_key (str): The Gemini API key for authentication.
        """
        if not api_key:
            raise ValueError("API key cannot be empty.")

        self.api_key = api_key
        # Configure the genai library with the API key upon initialization.
        genai.configure(api_key=self.api_key)

    def generate_code_for_component(self, logic_plan: str, coding_standard: str, target_language: str, feedback: Optional[str] = None) -> str:
        """
        Generates source code based on a logic plan and a coding standard,
        explicitly targeting a specific programming language.

        Args:
            logic_plan (str): The logic/pseudocode generated by the LogicAgent.
            coding_standard (str): The coding standard to be enforced.
            target_language (str): The programming language for the output code.
            feedback (Optional[str], optional): Discrepancy report from a code review.
                                                 Defaults to None.

        Returns:
            str: The generated source code for the component.
        """
        try:
            # Use the more capable model for code generation
            model = genai.GenerativeModel('gemini-1.5-pro-latest')

            # Dynamically build the prompt based on whether this is a first attempt or a correction
            if feedback:
                correction_prompt_part = f"""
                **IMPORTANT CONTEXT:** This is a second attempt to generate this code. A previous version failed a code review. You MUST address the following feedback and correct the code.

                **--- Code Review Feedback to Address ---**
                {feedback}
                """
                prompt_header = "You are an expert software developer. Your task is to CORRECT the previous code generation attempt based on the provided feedback."
            else:
                correction_prompt_part = ""
                prompt_header = "You are an expert software developer. Your task is to write clean, efficient, and production-ready source code based on a provided logical plan and a strict coding standard."

            prompt = f"""
            {prompt_header}

            **MANDATORY INSTRUCTIONS:**
            1.  **Target Language:** You MUST write the code in the following programming language: **{target_language}**.
            2.  **Strictly Adhere to Coding Standard:** You MUST follow all rules in the provided coding standard. This includes naming conventions, formatting, docstrings, comments, and structural principles.
            3.  **Implement Only the Provided Logic:** You MUST implement ONLY the logic and steps described in the logical plan. Do not add new features or make assumptions.
            4.  **Raw Code Output:** Your entire response MUST BE ONLY the raw source code for the component, including any necessary imports.
            5.  **No Citations:** Your output must NOT contain any citation markers (e.g., `[cite]`).

            {correction_prompt_part}

            **--- INPUT 1: The Logical Plan to Implement ---**
            ```
            {logic_plan}
            ```

            **--- INPUT 2: The Coding Standard to Follow ---**
            ```
            {coding_standard}
            ```

            **--- Generated Source Code (Language: {target_language}) ---**
            """

            response = model.generate_content(prompt)
            return response.text

        except Exception as e:
            error_message = f"An error occurred while communicating with the Gemini API: {e}"
            logging.error(error_message)
            return error_message